# Generated by Django 3.2 on 2021-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=120)),
                ('image', models.CharField(max_length=120)),
                ('lprice', models.IntegerField(max_length=50)),
                ('hprice', models.IntegerField(max_length=50)),
                ('mallName', models.CharField(max_length=120)),
                ('productId', models.IntegerField(max_length=50)),
                ('productType', models.IntegerField(max_length=50)),
                ('brand', models.CharField(max_length=120)),
                ('maker', models.CharField(max_length=120)),
                ('category1', models.CharField(max_length=120)),
                ('category2', models.CharField(max_length=120)),
                ('category3', models.CharField(max_length=120)),
                ('category4', models.CharField(max_length=120)),
            ],
        ),
    ]
