# Generated by Django 3.2 on 2021-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=120)),
                ('productId', models.IntegerField()),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('completeDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
