# Generated by Django 3.2 on 2021-04-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productId',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
