# Generated by Django 3.2 on 2021-04-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20210418_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
