# Generated by Django 3.2 on 2021-04-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_alter_order_completedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completeDate',
        ),
    ]
