# Generated by Django 3.2 on 2021-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_remove_order_completedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hprice',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lprice',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mallName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
